
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Nunu",
    "surname" : "Willump",
    "mail" : "disconunu@vinci.be",
    "campus" : "Woluwe-saint-lambert",
    "password" : "123"
}

###
GET http://localhost:5000/users


###
GET http://localhost:5000/users/lemaildepaul@vinci.be

###
DELETE http://localhost:5000/users/61b0ba611c4ccf9f3b6f94db

###
PATCH  http://localhost:5000/users/61b31f7a1627fd419e0f429b
Content-Type: application/json

{
    "name": "chap0pointulefifou",
    "IsAdmin" : true
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "mail" : "Paula.taches@vinci.be",
    "password" : "dragon"

}
###

POST http://localhost:5000/users/ratings
Content-Type: application/json

{
    "idRater" : "61b31f851627fd419e0f429c",
    "idRated" : "61b320411627fd419e0f429e",
    "like" : 1
}

###
PATCH http://localhost:5000/users/ratings
Content-Type: application/json

{
    "id" : "61b34250062746a8a2eb87c6",
    "idRater" : "61b31f851627fd419e0f429c",
    "idRated" : "61b320411627fd419e0f429e",
    "like" : -1

}

###

DELETE http://localhost:5000/users/ratings/61b34250062746a8a2eb87c6
