
POST http://localhost:5000/users
Content-Type: application/json

{
"Name":"le roi des badges",
"Surname":"sisi c est lui",
"Mail":"leroi@vinci.be",
"Campus":"Clos Chapelle-aux-Champs 43, 1200 Woluwe-Saint-Lambert",
"Password":"dragon"
}

###
GET http://localhost:5000/users


###
GET http://localhost:5000/users/lemaildepaul@vinci.be

###
DELETE http://localhost:5000/users/61b0ba611c4ccf9f3b6f94db

###
PATCH  http://localhost:5000/users/61b85d495f56381bab89f28d
Content-Type: application/json

{
    "Password": "dragon"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "mail" : "disconunu@vinci.be",
    "password" : "dragon"

}
###

POST http://localhost:5000/users/ratings
Content-Type: application/json

{
    "idRater" : "61b31f851627fd419e0f429c",
    "idRated" : "61b320411627fd419e0f429e",
    "like" : 1
}

###
PATCH http://localhost:5000/users/ratings
Content-Type: application/json

{
    "id" : "61b34250062746a8a2eb87c6",
    "idRater" : "61b31f851627fd419e0f429c",
    "idRated" : "61b320411627fd419e0f429e",
    "like" : -1

}

###

DELETE http://localhost:5000/users/ratings/61b34250062746a8a2eb87c6

###
PUT http://localhost:5000/users/imagePath/61b31f7a1627fd419e0f429b
Content-Type: application/json

{
    "FilePath" : "C:\\Users\\Psycho\\Pictures\\pometer.png",
    "FileName" : "pommeDeTerre.png"
}

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "Adress": "Place de l'Alma 3, 1200 Woluwe-Saint-Lambert",
    "Description" : "yo les gars",
    "Name" : "JE SUIS LE NOM LA",
    "Type" : "Loisirs",
    "SentType" : "ADonner",
    "SellerId" : "61b8961381180e04240fc1de"
}

###
PATCH http://localhost:5000/products/sell/61b8b8f1d221cf318aa9bf22/61b85d495f56381bab89f28d

###

GET http://localhost:5000/users/boughtProduct/61b85d495f56381bab89f28d

